AB#39080 add app permissions sample query: GET teams channels
LokiLabs/microsoft-graph-devx-content pull request #12
Opened 2021-07-19 20:06 UTC by acchiang

Copied from the other GET teams channels sample query, but with new generated GUID and added information in the tip to ensure the user knows to switch to user mode in order to get Teams IDs.

2021-07-22 21:44 UTC, omersayshi approved these changes

2021-07-23 11:41 UTC, AyuAi requested changes
I think for consistency, we should keep everything as beta and make sure the category labels correspond to such (otherwise they appear in different sections on the sample queries tab).

I know that two of these suggestions are not the queries that you added, but since you edited the indentation of the entire list so far, I thought it might as well be a good idea to add the changes here ^^

2021-07-23 11:41 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "category": "Microsoft Teams",
```suggestion
        "category": "Microsoft Teams (beta)",
```

2021-07-23 11:41 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "docLink": "https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&tabs=http",
```suggestion
        "category": "Microsoft Teams (beta)",
        "method": "GET",
        "humanName": "get list of members in team",
        "requestUrl": "/beta/teams/{team-id}/members",
        "docLink": "https://docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta",
```

2021-07-23 11:41 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "docLink": "https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/channel_list",
```suggestion
        "category": "Microsoft Teams (beta)",
        "method": "GET",
        "humanName": "channels of a team which I am member of",
        "requestUrl": "/beta/teams/{team-id}/channels",
        "docLink": "https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta",
```

2021-07-26 21:38 UTC, AyuAi approved these changes

2021-07-26 22:42 UTC, merged