AB#39081 add app permissions sample query: POST teams channels
LokiLabs/microsoft-graph-devx-content pull request #13
Opened 2021-07-19 20:18 UTC by acchiang

Copied from the other POST teams channels sample query, but with new generated GUID and added information in the tip to ensure the user knows to switch to user mode in order to get Teams IDs. 
Also added a space between the link and the period in the tip so that the period is not automatically added to the autofill input box when a user clicks on it.

2021-07-22 21:45 UTC, omersayshi approved these changes

2021-07-23 10:50 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "tip": "This query requires a team id.  To find the team id of teams you belong to, you can run: GET https://graph.microsoft.com/v1.0/me/joinedTeams .",
This bug has been patched as per [AD#39035](https://dev.azure.com/microsoftgarage/Intern%20GitHub/_sprints/taskboard/GI21%20-%20Graph%20Explorer/Intern%20GitHub/Y21-S/07?workitem=39035)! There is no need to remove the period anymore ^^

```suggestion
        "tip": "This query requires a team id.  To find the team id of teams you belong to, you can run: GET https://graph.microsoft.com/v1.0/me/joinedTeams.",
```

2021-07-23 11:45 UTC, AyuAi requested changes
If we don't use the beta tag for some of the queries, they end up in a separate drop-down. Maybe we want this? But I kind of assumed we have been prioritizing the beta queries because that's what I've seen before.

Lmk @omersayshi @acchiang 👀

2021-07-23 11:45 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "docLink": "https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/channel_post",
Shouldn't we be using beta? (I could be wrong)
```suggestion
        "category": "Microsoft Teams (beta)",
        "method": "POST",
        "humanName": "create channel",
        "requestUrl": "/beta/teams/{team-id}/channels",
        "docLink": "https://docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta",
```

2021-07-26 21:39 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "category": "Microsoft Teams",
```suggestion
        "category": "Microsoft Teams (beta)",
```

2021-07-26 23:55 UTC, AyuAi approved these changes

2021-07-26 23:56 UTC, AyuAi commented
LGTM! Be sure to test it before merging since there have been more commits added 🥺🙏

2021-07-27 16:49 UTC, acchiang commented
great callouts @AyuAi!

2021-07-27 16:49 UTC, merged