AB#39005 and AB#39077 Added get chat and get chat messages queries
LokiLabs/microsoft-graph-devx-content pull request #19
Opened 2021-07-22 13:50 UTC by omersayshi

### Overview

Adding chat queries to application mode.

### Testing Instructions

* Follow this instructions of this PR https://github.com/LokiLabs/microsoft-graph-explorer-v4/pull/43 to have the functionality on Graph Explorer
* {ADD_YOUR_BRANCH_NAME_HERE} here would be this branch's name {interns/omersayshi/39055-get-chat-query}

2021-07-22 21:48 UTC, gracet9182 approved these changes
Nice, ran the branch and saw them

2021-07-23 11:34 UTC, AyuAi requested changes
Make sure to use the (beta) tag on the category names! Otherwise, it shows up in a different category ^^;

2021-07-23 11:34 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "category": "Microsoft Teams",
```suggestion
        "category": "Microsoft Teams (beta)",
```

2021-07-23 11:34 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "category": "Microsoft Teams",
```suggestion
        "category": "Microsoft Teams (beta)",
```

2021-07-27 22:30 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "docLink": "https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&tabs=http",
```suggestion
        "docLink": "https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta",
```

2021-07-27 22:31 UTC, AyuAi commented on sample-queries/sample-queries.json
> +        "docLink": "https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-1.0&tabs=http",
```suggestion
        "docLink": "https://docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta",
```

2021-07-27 22:33 UTC, merged